# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeDataAPISample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YoutubeDataAPISample

pod 'GoogleSignIn'
pod "youtube-ios-player-helper", "~> 0.1.4"

pod 'Analytics', :git => 'https://github.com/primedata-ai/analytics-ios.git'

end
